// Embedded fallback data so the portal renders when opened directly as a file://
// (browsers block fetch() of local files). When served, app.js prefers the live
// ../output/tenders.json export from the Claude routine and ignores this.
// Keep this in sync with output/tenders.json.
window.SAMPLE_DATA = {
  "run_metadata": {
    "run_date": "2026-06-25",
    "coverage_summary": "Full sweep of Tier 1 government portals; sampled local government via VendorPanel, three GBEs, two universities, and a rotating set of Tier 3 corporate supplier portals.",
    "sources_checked": 27,
    "tenders_found": 12,
    "new_sources_found": 3,
    "gaps": [
      "Tenders WA search API returned HTTP 503 twice; results may be incomplete for WA.",
      "BHP supplier portal (SAP Ariba) requires registration to view full opportunity detail; captured public summary only.",
      "Sampled 40 of ~537 local councils on VendorPanel; remainder deferred to future runs."
    ],
    "recommended_seed_additions": [
      "Sydney Water supplier portal (Jaggaer) — active works packages observed",
      "University of Melbourne procurement page — recurring ICT panels",
      "EstimateOne — high subcontractor package volume for VIC/NSW construction"
    ]
  },
  "tenders": [
    {
      "dedup_key": "AusTender:CN-3845567",
      "source_name": "AusTender",
      "source_url": "https://www.tenders.gov.au",
      "source_type": "gov-commonwealth",
      "jurisdiction": "Commonwealth",
      "state": "Australia",
      "tender_id": "CN-3845567",
      "title": "Provision of Cloud Hosting and Managed Services",
      "description": "Whole-of-government cloud hosting panel refresh covering IaaS, PaaS and managed security services for Commonwealth agencies.",
      "buyer": "Digital Transformation Agency",
      "buyer_url": "https://www.dta.gov.au",
      "publish_date": "2026-06-24",
      "closing_date": "2026-07-22",
      "value": "$45,000,000",
      "category": "ICT",
      "procurement_type": "RFT",
      "current_status": "open",
      "access": "public",
      "tender_url": "https://www.tenders.gov.au/atm/show/CN-3845567",
      "tags": ["cloud", "managed-services", "panel", "ict"],
      "first_seen": "2026-06-25",
      "reasoning": "Discovered via AusTender ATM RSS feed, published in the last 24 hours.",
      "notes": ""
    },
    {
      "dedup_key": "eTendering NSW:RFT-2026-1188",
      "source_name": "eTendering NSW",
      "source_url": "https://www.tenders.nsw.gov.au",
      "source_type": "gov-state",
      "jurisdiction": "New South Wales",
      "state": "NSW",
      "tender_id": "RFT-2026-1188",
      "title": "Sydney Metro West — Systems Integration Services",
      "description": "Expression of interest for systems integration and testing services supporting the Sydney Metro West delivery program.",
      "buyer": "Transport for NSW",
      "buyer_url": "https://www.transport.nsw.gov.au",
      "publish_date": "2026-06-23",
      "closing_date": "2026-06-30",
      "value": "$120,000,000",
      "category": "Transport / Infrastructure",
      "procurement_type": "EOI",
      "current_status": "closing-soon",
      "access": "public",
      "tender_url": "https://www.tenders.nsw.gov.au/?event=public.rft.show&RFTUUID=RFT-2026-1188",
      "tags": ["rail", "infrastructure", "systems-integration"],
      "first_seen": "2026-06-25",
      "reasoning": "Found on eTendering NSW current opportunities list filtered to last 7 days.",
      "notes": "Closes within a week — flagged closing-soon."
    },
    {
      "dedup_key": "Buying for Victoria:SS-2026-0421",
      "source_name": "Buying for Victoria",
      "source_url": "https://www.tenders.vic.gov.au",
      "source_type": "gov-state",
      "jurisdiction": "Victoria",
      "state": "VIC",
      "tender_id": "SS-2026-0421",
      "title": "Mental Health Clinical Services Panel",
      "description": "Establishment of a standing offer panel for community mental health clinical services across metropolitan and regional Victoria.",
      "buyer": "Department of Health (VIC)",
      "buyer_url": "https://www.health.vic.gov.au",
      "publish_date": "2026-06-20",
      "closing_date": "2026-08-05",
      "value": "",
      "category": "Health",
      "procurement_type": "panel",
      "current_status": "open",
      "access": "public",
      "tender_url": "https://www.tenders.vic.gov.au/tender/view?id=SS-2026-0421",
      "tags": ["health", "mental-health", "panel"],
      "first_seen": "2026-06-25",
      "reasoning": "Listed on Buying for Victoria open tenders, health category.",
      "notes": "No published estimated value."
    },
    {
      "dedup_key": "QTenders:QLD-2026-3309",
      "source_name": "QTenders",
      "source_url": "https://qtenders.hpw.qld.gov.au",
      "source_type": "gov-state",
      "jurisdiction": "Queensland",
      "state": "QLD",
      "tender_id": "QLD-2026-3309",
      "title": "Bruce Highway Upgrade — Pavement Works",
      "description": "Request for tender for pavement rehabilitation and widening works on a section of the Bruce Highway.",
      "buyer": "Department of Transport and Main Roads",
      "buyer_url": "https://www.tmr.qld.gov.au",
      "publish_date": "2026-06-22",
      "closing_date": "2026-07-15",
      "value": "$8,500,000",
      "category": "Roads / Construction",
      "procurement_type": "RFT",
      "current_status": "open",
      "access": "free-registration",
      "tender_url": "https://qtenders.hpw.qld.gov.au/qtenders/tender/display/tender-details.do?id=QLD-2026-3309",
      "tags": ["roads", "civil", "construction"],
      "first_seen": "2026-06-25",
      "reasoning": "Captured from QTenders directory; note QTenders is migrating to VendorPanel.",
      "notes": "Full documents require free QTenders registration."
    },
    {
      "dedup_key": "VendorPanel:LismoreCC-Q2026-77",
      "source_name": "VendorPanel (Lismore City Council)",
      "source_url": "https://www.vendorpanel.com.au/publictenders.aspx",
      "source_type": "gov-local",
      "jurisdiction": "New South Wales",
      "state": "NSW",
      "tender_id": "LismoreCC-Q2026-77",
      "title": "Supply and Delivery of Road Construction Materials",
      "description": "Annual supply contract for road base, aggregate and asphalt materials for council works.",
      "buyer": "Lismore City Council",
      "buyer_url": "https://lismore.nsw.gov.au",
      "publish_date": "2026-06-21",
      "closing_date": "2026-07-09",
      "value": "$1,200,000",
      "category": "Materials / Local Government",
      "procurement_type": "RFQ",
      "current_status": "open",
      "access": "free-registration",
      "tender_url": "https://www.vendorpanel.com.au/publictenders.aspx",
      "tags": ["local-government", "materials", "roads"],
      "first_seen": "2026-06-25",
      "reasoning": "Found on VendorPanel public tenders board, the channel most NSW councils publish through.",
      "notes": "Buyer-originated via council's chosen platform — not an aggregator listing."
    },
    {
      "dedup_key": "Australia Post:AP-RFP-2026-019",
      "source_name": "Australia Post Supplier Portal",
      "source_url": "https://auspost.com.au/about-us/supplier-information",
      "source_type": "gov-business-enterprise",
      "jurisdiction": "Commonwealth",
      "state": "Australia",
      "tender_id": "AP-RFP-2026-019",
      "title": "Last-Mile Electric Delivery Fleet Supply",
      "description": "Request for proposal for the supply and servicing of electric delivery vehicles for metropolitan last-mile operations.",
      "buyer": "Australia Post",
      "buyer_url": "https://auspost.com.au",
      "publish_date": "2026-06-19",
      "closing_date": "2026-07-18",
      "value": "$30,000,000",
      "category": "Fleet / Logistics",
      "procurement_type": "RFP",
      "current_status": "open",
      "access": "free-registration",
      "tender_url": "https://auspost.com.au/about-us/supplier-information",
      "tags": ["gbe", "fleet", "ev", "logistics"],
      "first_seen": "2026-06-25",
      "reasoning": "Government Business Enterprise that publishes on its own supplier portal, not on AusTender.",
      "notes": ""
    },
    {
      "dedup_key": "Sydney Water:SW-2026-PW-204",
      "source_name": "Sydney Water Supplier Portal",
      "source_url": "https://www.sydneywater.com.au/about-us/work-with-us.html",
      "source_type": "gov-business-enterprise",
      "jurisdiction": "New South Wales",
      "state": "NSW",
      "tender_id": "SW-2026-PW-204",
      "title": "Wastewater Treatment Plant Mechanical Upgrade",
      "description": "Design and construction of mechanical and electrical upgrades to a major wastewater treatment facility.",
      "buyer": "Sydney Water",
      "buyer_url": "https://www.sydneywater.com.au",
      "publish_date": "2026-06-18",
      "closing_date": "2026-07-30",
      "value": "$22,000,000",
      "category": "Water / Infrastructure",
      "procurement_type": "RFT",
      "current_status": "open",
      "access": "free-registration",
      "tender_url": "https://www.sydneywater.com.au/about-us/work-with-us.html",
      "tags": ["water", "infrastructure", "jaggaer"],
      "first_seen": "2026-06-25",
      "reasoning": "Discovered via source-discovery sweep of state water corporations; Jaggaer-hosted supplier portal.",
      "notes": "New source candidate — see recommended_seed_additions."
    },
    {
      "dedup_key": "University of Melbourne:UoM-2026-ICT-58",
      "source_name": "University of Melbourne Procurement",
      "source_url": "https://www.unimelb.edu.au/procurement",
      "source_type": "university",
      "jurisdiction": "Victoria",
      "state": "VIC",
      "tender_id": "UoM-2026-ICT-58",
      "title": "Audio-Visual Equipment and Installation Panel",
      "description": "Establishment of a panel for the supply, installation and maintenance of audio-visual equipment across university campuses.",
      "buyer": "University of Melbourne",
      "buyer_url": "https://www.unimelb.edu.au",
      "publish_date": "2026-06-17",
      "closing_date": "2026-07-11",
      "value": "$5,000,000",
      "category": "ICT / Education",
      "procurement_type": "panel",
      "current_status": "open",
      "access": "public",
      "tender_url": "https://www.unimelb.edu.au/procurement/tenders",
      "tags": ["university", "av", "panel", "education"],
      "first_seen": "2026-06-25",
      "reasoning": "Universities procure independently; found on the institution's own procurement page.",
      "notes": ""
    },
    {
      "dedup_key": "BHP:ARIBA-DISC-771204",
      "source_name": "BHP Supplier (SAP Ariba)",
      "source_url": "https://www.bhp.com/suppliers",
      "source_type": "corporate",
      "jurisdiction": "Western Australia",
      "state": "WA",
      "tender_id": "ARIBA-DISC-771204",
      "title": "Conveyor Systems Maintenance Services — Pilbara",
      "description": "Sourcing event for conveyor maintenance and reliability services across Pilbara iron ore operations.",
      "buyer": "BHP",
      "buyer_url": "https://www.bhp.com",
      "publish_date": "2026-06-16",
      "closing_date": "2026-07-14",
      "value": "",
      "category": "Mining / Maintenance",
      "procurement_type": "sourcing-event",
      "current_status": "open",
      "access": "free-registration",
      "tender_url": "https://www.bhp.com/suppliers",
      "tags": ["mining", "maintenance", "ariba", "pilbara"],
      "first_seen": "2026-06-25",
      "reasoning": "Posted directly by the buyer on SAP Ariba Discovery; located via the company's own suppliers page.",
      "notes": "Registration required to view full scope; public summary captured."
    },
    {
      "dedup_key": "Telstra:TLS-RFP-2026-0334",
      "source_name": "Telstra Procurement",
      "source_url": "https://www.telstra.com.au/aboutus/our-company/suppliers",
      "source_type": "corporate",
      "jurisdiction": "Victoria",
      "state": "VIC",
      "tender_id": "TLS-RFP-2026-0334",
      "title": "Field Services Workforce Management Platform",
      "description": "Request for proposal for a SaaS workforce management and scheduling platform for national field operations.",
      "buyer": "Telstra",
      "buyer_url": "https://www.telstra.com.au",
      "publish_date": "2026-06-15",
      "closing_date": "2026-07-06",
      "value": "$12,000,000",
      "category": "ICT / Telecommunications",
      "procurement_type": "RFP",
      "current_status": "closing-soon",
      "access": "free-registration",
      "tender_url": "https://www.telstra.com.au/aboutus/our-company/suppliers",
      "tags": ["telco", "saas", "workforce", "coupa"],
      "first_seen": "2026-06-25",
      "reasoning": "Corporate supplier portal (Coupa); buyer-originated sourcing event.",
      "notes": ""
    },
    {
      "dedup_key": "EstimateOne:E1-2026-VIC-9921",
      "source_name": "EstimateOne",
      "source_url": "https://www.estimateone.com",
      "source_type": "construction-subcontract",
      "jurisdiction": "Victoria",
      "state": "VIC",
      "tender_id": "E1-2026-VIC-9921",
      "title": "Structural Steel Subcontract Package — CBD Tower",
      "description": "Head contractor invitation for structural steel supply and erection subcontractor quotes on a commercial tower project.",
      "buyer": "Multiplex (head contractor)",
      "buyer_url": "https://www.multiplex.global",
      "publish_date": "2026-06-24",
      "closing_date": "2026-07-08",
      "value": "",
      "category": "Construction / Subcontract",
      "procurement_type": "subcontractor-package",
      "current_status": "open",
      "access": "free-registration",
      "tender_url": "https://www.estimateone.com",
      "tags": ["construction", "subcontract", "structural-steel"],
      "first_seen": "2026-06-25",
      "reasoning": "Tier-1 builder invites subcontractor quotes via EstimateOne; buyer-originated work package.",
      "notes": "Parallel subcontractor market not visible on government portals."
    },
    {
      "dedup_key": "Tenders SA:SA-2026-0712",
      "source_name": "Tenders SA",
      "source_url": "https://www.tenders.sa.gov.au",
      "source_type": "gov-state",
      "jurisdiction": "South Australia",
      "state": "SA",
      "tender_id": "SA-2026-0712",
      "title": "School Modernisation Program — Builder Prequalification",
      "description": "Prequalification of builders for an upcoming program of school upgrade and modernisation works.",
      "buyer": "Department for Education (SA)",
      "buyer_url": "https://www.education.sa.gov.au",
      "publish_date": "2026-06-14",
      "closing_date": "2026-06-26",
      "value": "",
      "category": "Education / Construction",
      "procurement_type": "prequalification",
      "current_status": "closing-soon",
      "access": "public",
      "tender_url": "https://www.tenders.sa.gov.au/tender/view?id=SA-2026-0712",
      "tags": ["education", "construction", "prequalification"],
      "first_seen": "2026-06-25",
      "reasoning": "Tenders SA current opportunities, prequalification category.",
      "notes": "Closes tomorrow relative to run date."
    }
  ],
  "discovered_sources": [
    {
      "source_name": "Sydney Water Supplier Portal",
      "source_url": "https://www.sydneywater.com.au/about-us/work-with-us.html",
      "source_type": "gov-business-enterprise",
      "jurisdiction": "New South Wales",
      "platform": "Jaggaer",
      "access_method": "portal-registration",
      "feed_or_api_url": null,
      "is_new_source": true,
      "confidence": "high",
      "how_discovered": "Source-discovery sweep of state water corporations; followed 'work with us' from the corporate site.",
      "recommended_check_frequency": "weekly",
      "notes": "Active works packages observed; recommend adding to seed list."
    },
    {
      "source_name": "University of Melbourne Procurement",
      "source_url": "https://www.unimelb.edu.au/procurement",
      "source_type": "university",
      "jurisdiction": "Victoria",
      "platform": "custom",
      "access_method": "html",
      "feed_or_api_url": null,
      "is_new_source": true,
      "confidence": "high",
      "how_discovered": "Searched Group of Eight universities for independent procurement pages.",
      "recommended_check_frequency": "weekly",
      "notes": "Recurring ICT and AV panels."
    },
    {
      "source_name": "EstimateOne",
      "source_url": "https://www.estimateone.com",
      "source_type": "construction-subcontract",
      "jurisdiction": "National",
      "platform": "EstimateOne",
      "access_method": "portal-registration",
      "feed_or_api_url": null,
      "is_new_source": true,
      "confidence": "medium",
      "how_discovered": "Identified the platform Tier-1 builders use to issue subcontractor packages.",
      "recommended_check_frequency": "daily",
      "notes": "High subcontractor package volume for VIC/NSW; buyer-originated, not a paid reseller of others' notices."
    },
    {
      "source_name": "AusTender",
      "source_url": "https://www.tenders.gov.au",
      "source_type": "gov-commonwealth",
      "jurisdiction": "Commonwealth",
      "platform": "AusTender",
      "access_method": "rss",
      "feed_or_api_url": "https://www.tenders.gov.au/atm/rss",
      "is_new_source": false,
      "confidence": "high",
      "how_discovered": "Canonical seed source.",
      "recommended_check_frequency": "daily",
      "notes": "RSS feed for ATMs followed with pagination."
    },
    {
      "source_name": "VendorPanel Public Tenders",
      "source_url": "https://www.vendorpanel.com.au/publictenders.aspx",
      "source_type": "gov-local",
      "jurisdiction": "National",
      "platform": "VendorPanel",
      "access_method": "portal-registration",
      "feed_or_api_url": null,
      "is_new_source": false,
      "confidence": "high",
      "how_discovered": "Known channel that most Australian councils publish through.",
      "recommended_check_frequency": "daily",
      "notes": "Free to view, registration to respond."
    },
    {
      "source_name": "Quotations and Tenders Online (QTOL)",
      "source_url": "https://tendersonline.nt.gov.au",
      "source_type": "gov-state",
      "jurisdiction": "Northern Territory",
      "platform": "custom",
      "access_method": "html",
      "feed_or_api_url": null,
      "is_new_source": false,
      "confidence": "high",
      "how_discovered": "Canonical seed source (corrected from tenders.nt.gov.au).",
      "recommended_check_frequency": "daily",
      "notes": "NT central procurement portal."
    }
  ]
};
